version: '3'
services:
    node-api:
      container_name: node-api
      build: . 
      ports:
        - "3002:3002"

      environment:
        -  PORT=3002
        - CLOUDINARY_API_KEY=826488879423284
        - CLOUDINARY_API_SECRET=45NTb94cUlFiQaid2rHr31cV3bs
        - MONGODB_URL=mongodb://anaomart:omarashraf@ac-3cjch4l-shard-00-00.49mdvgj.mongodb.net:27017,ac-3cjch4l-shard-00-01.49mdvgj.mongodb.net:27017,ac-3cjch4l-shard-00-02.49mdvgj.mongodb.net:27017/?ssl=true&replicaSet=atlas-j20wdy-shard-0&authSource=admin&retryWrites=true&w=majority
    nginx:
      image: nginx:stable-alpine
      ports:
        - "80:80"
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
       - node-api
